In [2]:
from bs4 import BeautifulSoup
from urllib import request
from lxml.html import fromstring 
import re
import csv
import pandas as pd


wiki = "http://en.wikipedia.org/wiki/List_of_England_Test_cricket_records"
header = {'User-Agent': 'Mozilla/5.0'} #Needed to prevent 403 error on Wikipedia
req = request.Request(wiki,headers=header)
page = request.urlopen(req)

soup = BeautifulSoup(page, "lxml")

tables = soup.find_all('table')

for table in tables:
    tmp = table.find_all('tr')
    first = tmp[0]
    allRows = tmp[1:]
    headers = [header.get_text() for header in first.find_all('th')]
    results = [[data.get_text() for data in row.find_all('td')] for row in allRows]
    rowspan = []

    for no, tr in enumerate(allRows):
        tmp = []
        for td_no, data in enumerate(tr.find_all('td')):
            #print  (repr(tr.getText()))
            if data.has_attr("rowspan"):
                rowspan.append((no, td_no, int(data["rowspan"]), data.get_text()))
    if rowspan:
        for i in rowspan:
            # tr value of rowspan in present in 1th place in results
            for j in range(1, i[2]):
                #- Add value in next tr.
                results[i[0]+j].insert(i[1], i[3])
    df = pd.DataFrame(data=results, columns=headers)
    print (df)

Empty DataFrame
Columns: []
Index: []
       Team     1st Test Matches  Won Lost Drawn Tied  % Won
0   England  March, 1877     969  346  282   341    0  35.70
      Opposition       Span Matches  Won Lost Drawn Tied   % Won
0      Australia  1877–2015     341  108  140    93    0   31.67
1     Bangladesh  2003–2010       8    8    0     0    0  100.00
2          India  1932–2014     112   43   21    48    0   38.39
3    New Zealand  1930–2015     101   48    9    44    0   47.52
4       Pakistan  1954–2015      77   22   18    37    0   28.57
5   South Africa  1889–2016     145   58   32    55    0   40.00
6      Sri Lanka  1982–2014      28   10    8    10    0   35.71
7    West Indies  1928–2015     151   46   54    50    0   30.46
8       Zimbabwe  1996–2003       6    3    0     3    0   50.00
  Rank   Score         Opposition                     Venue  \
0    1  903/7d     vs.  Australia                  The Oval
1    2     849   vs.  West Indies               Sabina Park
2    3  710/7d         vs.  India  Edgbaston Cricket Ground
3    4  658/8d     vs.  Australia              Trent Bridge
4    5   654/5  vs.  South Africa  Sahara Stadium Kingsmead
5    6  653/4d         vs.  India     Lord's Cricket Ground
6    7  652/7d         vs.  India           Chepauk Stadium
7    8     644     vs.  Australia     Sydney Cricket Ground
8    9     636     vs.  Australia     Sydney Cricket Ground
9   10  633/5d         vs.  India  Edgbaston Cricket Ground

                                  Place  Year Result
0       London, England, United Kingdom  1938    Won
1                     Kingston, Jamaica  1930   Draw
2   Birmingham, England, United Kingdom  2011    Won
3   Nottingham, England, United Kingdom  1938   Draw
4                  Durban, South Africa  1939   Draw
5       London, England, United Kingdom  1990    Won
6                        Chennai, India  1985    Won
7                     Sydney, Australia  2011    Won
8                     Sydney, Australia  1928    Won
9   Birmingham, England, United Kingdom  1979    Won
  Rank Score      Opposition                     Venue  \
0    1    45    v  Australia     Sydney Cricket Ground
1    2    46  v  West Indies         Queen's Park Oval
2    3    51  v  West Indies               Sabina Park
3    4    52    v  Australia                  The Oval
4    5    53    v  Australia     Lord's Cricket Ground
5    6    61    v  Australia  Melbourne Cricket Ground
6    6    61    v  Australia  Melbourne Cricket Ground
7    8    62    v  Australia     Lord's Cricket Ground
8    9    64  v  New Zealand             Basin Reserve
9   10    65    v  Australia     Sydney Cricket Ground

                                 Place     Year Result
0                    Sydney, Australia  1886/87    Won
1   Port of Spain, Trinidad and Tobago     1994   Lost
2                    Kingston, Jamaica     2009   Lost
3      London, England, United Kingdom     1948   Lost
4      London, England, United Kingdom     1888   Lost
5                 Melbourne, Australia  1903/04   Lost
6                 Melbourne, Australia  1901/02   Lost
7      London, England, United Kingdom     1888   Lost
8              Wellington, New Zealand  1977/78   Lost
9                    Sydney, Australia  1894/95    Won
  Rank                Margin        Opposition                     Venue  \
0    1  Innings and 579 runs    vs.  Australia                  The Oval
1    2  Innings and 285 runs        vs.  India     Lord's Cricket Ground
2    3  Innings and 283 runs  vs.  West Indies        Headingley Stadium
3    4  Innings and 261 runs   vs.  Bangladesh     Lord's Cricket Ground
4    5  Innings and 244 runs        vs.  India                  The Oval
5    6  Innings and 242 runs        vs.  India  Edgbaston Cricket Ground
6    7  Innings and 237 runs  vs.  West Indies                  The Oval
7    8  Innings and 230 runs    vs.  Australia             Adelaide Oval
8   9=  Innings and 225 runs    vs.  Australia  Melbourne Cricket Ground
9   9=  Innings and 225 runs     vs.  Pakistan     Lord's Cricket Ground

                                  Place   Season
0       London, England, United Kingdom     1938
1       London, England, United Kingdom     1974
2        Leeds, England, United Kingdom     2007
3       London, England, United Kingdom     2005
4       London, England, United Kingdom     2014
5   Birmingham, England, United Kingdom     2011
6       London, England, United Kingdom     1957
7                   Adelaide, Australia  1891/92
8                  Melbourne, Australia  1911/12
9       London, England, United Kingdom     2010
  Rank    Margin         Opposition                          Venue  \
0    1  675 runs     vs.  Australia        Brisbane Cricket Ground
1    2  354 runs      vs.  Pakistan    Trent Bridge Cricket Ground
2    3  347 runs     vs.  Australia          Lord's Cricket Ground
3    4  338 runs     vs.  Australia                  Adelaide Oval
4    5  329 runs    vs.  Bangladesh  Zohur Ahmed Chowdhury Stadium
5    6  322 runs     vs.  Australia        Brisbane Cricket Ground
6    7  319 runs         vs.  India    Trent Bridge Cricket Ground
7    8  312 runs  vs.  South Africa        Newlands Cricket Ground
8    9  299 runs     vs.  Australia          Sydney Cricket Ground
9   10  289 runs     vs.  Australia                       The Oval

                                  Place Season
0                   Brisbane, Australia   1928
1   Nottingham, England, United Kingdom   2010
2       London, England, United Kingdom   2013
3                   Adelaide, Australia   1933
4                Chittagong, Bangladesh   2003
5                   Brisbane, Australia   1936
6   Nottingham, England, United Kingdom   2011
7               Cape Town, South Africa   1957
8                     Sydney, Australia   1971
9       London, England, United Kingdom   1926
  Rank       Opponent No. wins            Most recent venue  \
0    1   South Africa        6        Lord's Cricket Ground
1   2=    West Indies        4        Lord's Cricket Ground
2   2=          India        4            Brabourne Stadium
3    4      Australia        3        Sydney Cricket Ground
4    5       Pakistan        2  Trent Bridge Cricket Ground
5    6      Sri Lanka        1  Old Trafford Cricket Ground

                      Most recent place Season
0       London, England, United Kingdom   1951
1   Birmingham, England, United Kingdom   2009
2                         Mumbai, India   2012
3                     Sydney, Australia   1932
4   Nottingham, England, United Kingdom   1967
5   Manchester, England, United Kingdom   2002
  Rank Appearances            Player          Span
0    1         133      Alec Stewart     1990–2003
1    2         126     Alastair Cook  2006–present
2    3         118          Ian Bell     2004–2015
3    3         118      Graham Gooch     1975–1995
4    5         117       David Gower     1978–1992
5    6         115  Michael Atherton     1989–2001
6    7         114     Colin Cowdrey     1954–1975
7    8         113    James Anderson  2003–present
8    9         108  Geoffrey Boycott     1964–1982
9   10         104   Kevin Pietersen     2005–2014
  Rank   Runs            Player Matches Average   Career Span
0    1  9,964     Alastair Cook     126   46.56  2006–present
1    2  8,900      Graham Gooch     118   42.58     1975–1995
2    3  8,463      Alec Stewart     133   39.54     1990–2003
3    4  8,231       David Gower     117   44.25     1978–1992
4    5  8,181   Kevin Pietersen     104   47.28     2005–2014
5    6  8,114     Geoff Boycott     108   47.72     1964–1982
6    7  7,728  Michael Atherton     115   37.69     1989–2001
7    8  7,727          Ian Bell     118   42.69     2004–2015
8    9  7,624     Colin Cowdrey     114   44.06     1954–1975
9   10  7,249     Wally Hammond      85   58.45     1927–1947
  Rank Hundreds           Player Matches   Runs Average   Career Span
0    1       28    Alastair Cook     126  9,964   46.56  2006–present
1    2       23  Kevin Pietersen     104  8,181   47.28     2005–2014
2    3       22    Wally Hammond      85  7,249   58.45     1927–1947
3    3       22    Colin Cowdrey     114  7,624   44.06     1954–1975
4    3       22    Geoff Boycott     108  8,114   47.72     1964–1982
5    3       22         Ian Bell     118  7,727   42.69     2004–2015
6    7       21   Andrew Strauss     100  7,037   40.91     2004–2012
7    8       20   Ken Barrington      82  6,806   58.67     1955–1968
8    8       20     Graham Gooch     118  8,900   42.58     1975–1995
9   10       19       Len Hutton      79  6,971   56.67     1937–1955
  No. Score            Batsmen           Against  \
0   1   364         Len Hutton    vs.  Australia
1   2  336*      Wally Hammond  vs.  New Zealand
2   3   333       Graham Gooch        vs.  India
3   4   325       Andy Sandham  vs.  West Indies
4   5  310*        John Edrich  vs.  New Zealand
5   6   294      Alastair Cook        vs.  India
6   7   287         Tip Foster    vs.  Australia
7   8  285*          Peter May  vs.  West Indies
8   9   278      Denis Compton     vs.  Pakistan
9  10   263  Alastair Cook (2)     vs.  Pakistan

                        Stadium                                 Place  Year
0                      The Oval       London, England, United Kingdom  1938
1                     Eden Park                 Auckland, New Zealand  1933
2         Lord's Cricket Ground       London, England, United Kingdom  1990
3                   Sabina Park                     Kingston, Jamaica  1930
4            Headingley Stadium        Leeds, England, United Kingdom  1965
5      Edgbaston Cricket Ground   Birmingham, England, United Kingdom  2011
6         Sydney Cricket Ground                     Sydney, Australia  1903
7      Edgbaston Cricket Ground   Birmingham, England, United Kingdom  1957
8   Trent Bridge Cricket Ground   Nottingham, England, United Kingdom  1954
9  Sheikh Zayed Cricket Stadium       Abu Dhabi, United Arab Emirates  2015
  Rank      Wickets           Player Matches Average         Years
0    1  433 wickets   James Anderson     113   29.18  2003–present
1    2  383 wickets       Ian Botham     102   28.40     1977–1992
2    3  333 wickets     Stuart Broad      91   28.66  2007–present
3    4  325 wickets       Bob Willis      90   25.20     1971–1984
4    5  307 wickets     Fred Trueman      67   21.57     1952–1965
5    6  297 wickets  Derek Underwood      86   25.83     1966–1982
6    7  255 wickets     Graeme Swann      60   29.96     2008–2013
7    8  252 wickets    Brian Statham      70   24.84     1951–1965
8    9  248 wickets  Matthew Hoggard      67   30.50     2000–2008
9   10  236 wickets      Alec Bedser      51   24.89     1946–1955
   Rank  5s           Player Matches Wickets    BBI Average         Years
0     1  27       Ian Botham     102     383   8/34   28.40     1977–1992
1     2  24    Sydney Barnes      27     189  9/103   16.43     1901–1914
2     3  18   James Anderson     113     433   7/43   29.18  2003–present
3     4  17     Graeme Swann      60     255   6/65   29.96     2008–2013
4     4  17     Fred Trueman      67     307   8/31   21.57     1952–1965
5     4  17  Derek Underwood      86     297   8/51   25.83     1966–1982
6     7  16       Bob Willis      90     325   8/43   25.20     1971–1984
7     8  15      Alec Bedser      51     236   7/44   24.89     1946–1955
8     8  15     Stuart Broad      91     333   8/15   28.66  2007–present
9    10  13     Andy Caddick      62     234   7/46   29.91     1993–2003
10   10  13     Angus Fraser      46     177   8/53   27.32     1989–1998
   No. Figures              Bowler            Against  \
0    1   10/53           Jim Laker     vs.  Australia
1    2    9/28      George Lohmann  vs.  South Africa
2    3    9/37       Jim Laker (2)     vs.  Australia
3    4    9/57       Devon Malcolm  vs.  South Africa
4    5   9/103       Sydney Barnes  vs.  South Africa
5    6     8/7  George Lohmann (2)  vs.  South Africa
6    7    8/11       Johnny Briggs  vs.  South Africa
7    8    8/15        Stuart Broad     vs.  Australia
8    9    8/29   Sydney Barnes (2)  vs.  South Africa
9   10    8/31        Fred Trueman         vs.  India
10  11    8/34          Ian Botham      vs.  Pakistan

                        Stadium                                 Place  Year
0   Old Trafford Cricket Ground   Manchester, England, United Kingdom  1956
1                 Old Wanderers            Johannesburg, South Africa  1896
2   Old Trafford Cricket Ground   Manchester, England, United Kingdom  1956
3                      The Oval       London, England, United Kingdom  1994
4                 Old Wanderers            Johannesburg, South Africa  1913
5              St George's Park          Port Elizabeth, South Africa  1896
6       Newlands Cricket Ground               Cape Town, South Africa  1889
7                  Trent Bridge                   Nottingham, England  2015
8                      The Oval       London, England, United Kingdom  1913
9   Old Trafford Cricket Ground   Manchester, England, United Kingdom  1952
10        Lord's Cricket Ground       London, England, United Kingdom  1978
  No. Score                        Batsmen            Against  \
0   1   359   Len Hutton & Cyril Washbrook  vs.  South Africa
1   2   382   Len Hutton & Maurice Leyland     vs.  Australia
2   3   370   Bill Edrich & Dennis Compton  vs.  South Africa
3   4   411      Peter May & Colin Cowdrey   vs.  West Indies
4   5   254    Keith Fletcher & Tony Greig         vs.  India
5   6   399    Ben Stokes & Jonny Bairstow  vs.  South Africa
6   7   197       M.J.K. Smith & Jim Parks   vs.  West Indies
7   8   332  Jonathan Trott & Stuart Broad      vs.  Pakistan
8   9  163*     Colin Cowdrey & Alan Smith   vs.  New Zealand
9  10   198      Joe Root & James Anderson         vs.  India

                       Stadium                                 Place  Year
0                   Ellis Park            Johannesburg, South Africa  1948
1                     The Oval       London, England, United Kingdom  1938
2        Lord's Cricket Ground       London, England, United Kingdom  1947
3     Edgbaston Cricket Ground   Birmingham, England, United Kingdom  1957
4            Brabourne Stadium                         Mumbai, India  1973
5      Newlands Cricket Ground               Cape Town, South Africa  2016
6            Queen's Park Oval      Port of Spain, Trinidad & Tobago  1960
7        Lord's Cricket Ground       London, England, United Kingdom  2010
8                Basin Reserve               Wellington, New Zealand  1963
9  Trent Bridge Cricket Ground   Nottingham, England, United Kingdom  2014
  No.      Wicket Score                        Batsmen            Against  \
0   1  4th wicket   411      Peter May & Colin Cowdrey   vs.  West Indies
1   2  6th wicket   399    Ben Stokes & Jonny Bairstow  vs.  South Africa
2   3  2nd wicket   382   Len Hutton & Maurice Leyland     vs.  Australia
3   4  3rd wicket   370   Bill Edrich & Dennis Compton  vs.  South Africa
4   5  2nd wicket   369   John Edrich & Ken Barrington   vs.  New Zealand
5   6  1st wicket   359   Len Hutton & Cyril Washbrook  vs.  South Africa
6   7  2nd wicket   351     Graham Gooch & David Gower     vs.  Australia
7   8  3rd wicket   350     Ian Bell & Kevin Pietersen         vs.  India
8   9  8th wicket   332  Jonathan Trott & Stuart Broad      vs.  Pakistan
9  10  2nd wicket   331     Tim Robinson & David Gower     vs.  Australia

                    Stadium                                 Place  Year
0  Edgbaston Cricket Ground   Birmingham, England, United Kingdom  1957
1   Newlands Cricket Ground               Cape Town, South Africa  2016
2                  The Oval       London, England, United Kingdom  1938
3     Lord's Cricket Ground       London, England, United Kingdom  1947
4        Headingley Stadium        Leeds, England, United Kingdom  1965
5                Ellis Park            Johannesburg, South Africa  1948
6                  The Oval       London, England, United Kingdom  1985
7                  The Oval       London, England, United Kingdom  2011
8     Lord's Cricket Ground       London, England, United Kingdom  2010
9  Edgbaston Cricket Ground   Birmingham, England, United Kingdom  1985
Empty DataFrame
Columns: []
Index: []
                 \n\n\nv\nt\ne\n\n\nCricket records\n
0                                                None
1
2   \n\n\nTest records\n(Australia\nBangladesh\nEn...
3
4   \n\n\nTest batting averages\nFive-wicket hauls...
5
6   \n\n\nODI records\n(Australia\nBangladesh\nEng...
7
8   \n\n\nODI batting averages\nFive-wicket hauls ...
9
10  \n\n\nT20I records\n(Australia\nBangladesh\nEn...
11
12  \n\n\nMiscellaneous\n(Batsmen with 10000+ Test...
13
14  \n\n\nBowlers with 300 Test wickets\nBowlers w...
15
16  \n\n\nWorld Cup records\nFirst-class records\n...
17
18  \n\n\nWomen's Test records\nWomen's One Day In...
19
20  \n\n\nWomen's Test centuries\nWomen's ODI cent...
21
                 \n\n\nv\nt\ne\n\n\nCricket records\n
0
1   \n\n\nTest records\n(Australia\nBangladesh\nEn...
2
3   \n\n\nTest batting averages\nFive-wicket hauls...
4
5   \n\n\nODI records\n(Australia\nBangladesh\nEng...
6
7   \n\n\nODI batting averages\nFive-wicket hauls ...
8
9   \n\n\nT20I records\n(Australia\nBangladesh\nEn...
10
11  \n\n\nMiscellaneous\n(Batsmen with 10000+ Test...
12
13  \n\n\nBowlers with 300 Test wickets\nBowlers w...
14
15  \n\n\nWorld Cup records\nFirst-class records\n...
16
17  \n\n\nWomen's Test records\nWomen's One Day In...
18
19  \n\n\nWomen's Test centuries\nWomen's ODI cent...
20